pipeline {
    agent any

    stages {
        stage('Clonar repositorio'){
            steps {
                git branch: 'main',
                credentialsId: 'git-jenkins',
                url: 'https://github.com/codentide/ea3-wt.git'
            }
        }

        stage('Construir docker'){
            steps {
                    script {
                        withCredentials([
                            string(credentialsId: 'MONGO_URI', variable: 'MONGO_URI')
                        ]) {
                            sh """
                            cd monolithic-app
                            docker build --build-arg MONGO_URI=${MONGO_URI} -t monolithic-app:v1 .
                            """

                        }
                    }
                }
        }


        stage('Desplegar Docker'){
            steps {
                script {
                    withCredentials([
                            string(credentialsId: 'MONGO_URI', variable: 'MONGO_URI')
                    ]) {
                        sh """
                            docker-compose -f docker-compose.yml up -d
                        """
                    }
                }
            }
        }
    }
}